[package]
name = "wasmedge-vlm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
wasmedge-wasi-nn = "0.8.0"
rust_processor = { git = "https://github.com/second-state/wasi_processor", subdirectory = "processor", branch = "main" }