[package]
name = "im2tensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = {version = "0.63", features = ["clang-runtime"]}
anyhow = "1.0.58"
structopt = "0.3.26"
thiserror = "1.0.31"