[package]
name = "wasmedge-ggml-gemma-3"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
wasmedge-wasi-nn = "0.7.1"

[[bin]]
name = "wasmedge-ggml-gemma-3"
path = "src/main.rs"

[[bin]]
name = "wasmedge-ggml-gemma-3-base64"
path = "src/base64.rs"
