[package]
name = "openvinogenai-deepseek-raw"
version = "0.1.0"
authors = ["Second-State"]
readme = "README.md"
edition = "2021"
publish = false

[dependencies]
serde_json = "1.0"
wasmedge-wasi-nn = {git = "https://github.com/LFsWang/wasmedge-wasi-nn", branch = "ggml"}
hound = "3.4"

[workspace]
