# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

env:
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build WasmEdge Wasi-NN with OpenVINO backend using g++
        env: 
          CMAKE_BUILD_TYPE: "Release"
          OPENVINO_VERSION: "2021.4.582"
          OPENVINO_YEAR: "2021"
        run: |
          git clone https://github.com/WasmEdge/WasmEdge -b proposal/wasi_nn --recursive
          chmod +x ./.github/scripts/build.sh
          bash ./.github/scripts/build.sh

      # Runs a single command using the runners shell
      - name: Build and run Rust example
        run: |
          chmod +x ./.github/scripts/test_rust.sh
          bash ./.github/scripts/test_rust.sh
